JSON_CHARCTERS = ["Images", "Main Characters"]
PATH_CHARCTERS = "data/Images/Main Characters"

WINDOWS_SCREEN = (960, 720)

DISPLAY_SIZE = (4 * 150, 3 * 150)

RATIO = (WINDOWS_SCREEN[0] / DISPLAY_SIZE[0], WINDOWS_SCREEN[1] / DISPLAY_SIZE[1])

IMAGE_SIZE = (32, 32)
